CUDA_VISIBLE_DEVICES=0,1 python -m flashrag.retriever.index_builder \
    --retrieval_method bge \
    --model_path /inspire/hdd/ws-8207e9e2-e733-4eec-a475-cfa1c36480ba/embodied-multimodality/public/yli/workspace/Model/BAAI/bge-large-en-v1.5 \
    --corpus_path /inspire/hdd/ws-8207e9e2-e733-4eec-a475-cfa1c36480ba/embodied-multimodality/public/yli/workspace/Datasets/Tevatron/wikipedia-nq-corpus-flashragformat/processed_corpus.jsonl \
    --save_dir /inspire/hdd/ws-8207e9e2-e733-4eec-a475-cfa1c36480ba/embodied-multimodality/public/yli/workspace/Datasets/Tevatron/wikipedia-nq-corpus-flashragformat/index_bge_large \
    --use_fp16 \
    --max_length 512 \
    --batch_size 512 \
    --pooling_method cls \
    --faiss_type Flat \
    --save_embedding
